project:
  type: website
  output-dir: docs

lang: es

website:
  title: "NOCTUA+ <img src='images/seo.png' height='50' style='padding-left:30px'><img src='images/noctua2.png' height='50' style='padding-left:20px'><img src='images/uam.png' height='50' style='padding-left:20px'>"
  navbar:
    right:
      - href: index.qmd
        text: Inicio
      - href: proyecto.qmd
        text: El proyecto
      - href: mapa.qmd
        text: Mapa resumen
      - href: participar.qmd
        text: ¿Cómo participar?

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    # include-in-header: header.html

editor: visual

